<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class InventorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()

    {

        DB::table('inventories')->insert([
            'product_name' => 'ALX-ET1-CAB11',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Elite 8300 MT',
            'product_type' => 'CALCULATOR',
            'product_number' => '10:60:4B:87:99:EA',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.1',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.3.63',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'HP',
            'product_model' => 'M428fdn',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.1',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => 'USB',]);
        DB::table('inventories')->insert([
            'product_name' => 'Cisco IP 7912',
            'product_vendor' => 'Cisco ',
            'product_model' => '7912',
            'product_type' => 'Telefon',
            'product_number' => '00:14:F2:9E:37:89',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.1',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.15.103',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-Et2-CAB22',
            'product_vendor' => 'Dell Inc.',
            'product_model' => 'OptiPlex 990',
            'product_type' => 'CALCULATOR',
            'product_number' => '78:2B:CB:90:93:A6',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.2 ',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.4.102',]);
        DB::table('inventories')->insert([
            'product_name' => 'MM-st2',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP 250 G7 Notebook PC',
            'product_type' => 'LAPTOP',
            'product_number' => '00:68:EB:79:B5:7C',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.2 ',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.7.139',]);
        DB::table('inventories')->insert([
            'product_name' => 'HP050D06',
            'product_vendor' => 'HP',
            'product_model' => 'M428fdn',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => '30:24:A9:05:0D:06',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.2',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.7.102',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'Panasonic',
            'product_model' => '',
            'product_type' => 'Telefon fix',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.2',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'Zebra',
            'product_model' => 'ZD410',
            'product_type' => 'IMPRIMANTA Etichete ',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.2',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => 'USB',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'TP-LINK',
            'product_model' => 'TL-SF1008D',
            'product_type' => 'SWITCH',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.2',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '',]);
        DB::table('inventories')->insert([
            'product_name' => 'alx-et1-cab18',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Elite 8300 CMT',
            'product_type' => 'CALCULATOR',
            'product_number' => 'B4:B5:2F:AD:F7:4A',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.3',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.3.115',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'HP',
            'product_model' => '1102w',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.3',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => 'USB',]);
        DB::table('inventories')->insert([
            'product_name' => 'Cisco IP 7912',
            'product_vendor' => 'Cisco',
            'product_model' => '7912',
            'product_type' => 'Telefon',
            'product_number' => '00:15:63:FF:5F:B7',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.3',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.15.181',]);
        DB::table('inventories')->insert([
            'product_name' => 'alxet1cab14',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Elite 8300 CMT',
            'product_type' => 'CALCULATOR',
            'product_number' => 'EC:08:6B:03:48:67',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.4',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.2.96',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'HP',
            'product_model' => '1102',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.4',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => 'USB',]);
        DB::table('inventories')->insert([
            'product_name' => 'Cisco IP 7912',
            'product_vendor' => 'Cisco',
            'product_model' => '7912',
            'product_type' => 'Telefon',
            'product_number' => '00:14:F2:75:28:F0',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.4',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.15.82',]);
        DB::table('inventories')->insert([
            'product_name' => 'alx-et1-cab15a',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Pro 6300 MT',
            'product_type' => 'CALCULATOR',
            'product_number' => '74:46:A0:B1:36:DC',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.5',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.4.180',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'HP',
            'product_model' => '1102',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.5',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => 'USB',]);
        DB::table('inventories')->insert([
            'product_name' => 'Cisco IP 7912',
            'product_vendor' => 'Cisco',
            'product_model' => '7912',
            'product_type' => 'Telefon',
            'product_number' => '00:19:06:96:5C:7C',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.5',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.15.20',]);
        DB::table('inventories')->insert([
            'product_name' => 'CabinetMF-1-6',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq 6200 Pro MT PC',
            'product_type' => 'CALCULATOR',
            'product_number' => 'E8:39:35:5C:44:0F',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.6',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.7.106',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'HP',
            'product_model' => '428fdn',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.6',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => 'USB',]);
        DB::table('inventories')->insert([
            'product_name' => 'Cisco IP 7912',
            'product_vendor' => 'Cisco',
            'product_model' => '7912',
            'product_type' => 'Telefon',
            'product_number' => '00:14:A8:AC:E7:F4',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.6',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.15.112',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'EPSON',
            'product_model' => ' LX350',
            'product_type' => 'IMPRIMANTA Matriciala',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.6',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => 'USB',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-ET1-CAB17',
            'product_vendor' => '',
            'product_model' => '',
            'product_type' => 'CALCULATOR',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.7',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.7.53',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'HP',
            'product_model' => '1102',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.7',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => 'USB',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'Panasonic',
            'product_model' => '',
            'product_type' => 'Telefon fix',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.7',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-ET1CAB18',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Elite 8300 CMT',
            'product_type' => 'CALCULATOR',
            'product_number' => '10:60:4B:85:64:ED',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.8',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.3.57',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'HP',
            'product_model' => 'M402n',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.8',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => 'USB',]);
        DB::table('inventories')->insert([
            'product_name' => 'Cisco IP 7912',
            'product_vendor' => 'Cisco',
            'product_model' => '7912',
            'product_type' => 'Telefon',
            'product_number' => '00:14:F2:75:22:D4',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.8',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.15.91',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-ET1-CAB19',
            'product_vendor' => '',
            'product_model' => '',
            'product_type' => 'CALCULATOR',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.9',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.3.61',]);
        DB::table('inventories')->insert([
            'product_name' => 'Cisco IP 7912',
            'product_vendor' => 'Cisco',
            'product_model' => '7912',
            'product_type' => 'Telefon',
            'product_number' => '00:14:F2:75:23:BB',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.9',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.15.105',]);
        DB::table('inventories')->insert([
            'product_name' => 'alx-et1-cab1-10',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Pro 6300 MT',
            'product_type' => 'CALCULATOR',
            'product_number' => 'B4:B5:2F:BB:E6:E4',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.10',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.3.62',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'HP',
            'product_model' => '107w',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.10',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => 'USB',]);
        DB::table('inventories')->insert([
            'product_name' => 'Cisco IP 7912',
            'product_vendor' => 'Cisco',
            'product_model' => '7912',
            'product_type' => 'Telefon',
            'product_number' => '00:17:59:3F:5B:44',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.10',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.15.134',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-ET1-REC1-3',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Elite 8300 MT',
            'product_type' => 'CALCULATOR',
            'product_number' => '10:60:4B:82:BA:C9',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.11',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.3.65',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'HP',
            'product_model' => '107w',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.11',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => 'USB',]);
        DB::table('inventories')->insert([
            'product_name' => 'Cisco IP 7912',
            'product_vendor' => 'Cisco',
            'product_model' => '7912',
            'product_type' => 'Telefon',
            'product_number' => '00:14:A9:64:07:90',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.11',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.15.107',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-PAR-AIS3-1',
            'product_vendor' => 'MSI',
            'product_model' => 'MSI-7817',
            'product_type' => 'CALCULATOR',
            'product_number' => '44:8A:5B:CA:45:1B',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.12 (ECOGRAF)',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.3.41',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'HP',
            'product_model' => '1005',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.12 (ECOGRAF)',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => 'USB',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-ET1-CAB113',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Pro 6300 MT',
            'product_type' => 'CALCULATOR',
            'product_number' => '6C:3B:E5:2D:E0:C5',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.13',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.4.153',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'HP',
            'product_model' => 'M402n',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.13',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => 'USB',]);
        DB::table('inventories')->insert([
            'product_name' => 'Cisco IP 7912',
            'product_vendor' => 'Cisco',
            'product_model' => '7912',
            'product_type' => 'Telefon',
            'product_number' => '00:11:20:D3:CF:5D',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.13',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.15.161',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-ET1-CAB1-14',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Elite 8300 MT',
            'product_type' => 'CALCULATOR',
            'product_number' => '6C:3B:E5:36:CE:AD',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.14',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.6.62',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'HP',
            'product_model' => 'M402n',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.14',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '',]);
        DB::table('inventories')->insert([
            'product_name' => 'Cisco IP 7912',
            'product_vendor' => 'Cisco',
            'product_model' => '7912',
            'product_type' => 'Telefon',
            'product_number' => '00:11:20:32:B5:BA',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.14',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.15.162',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-ET1-CAB1-15',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Elite 8300 CMT',
            'product_type' => 'CALCULATOR',
            'product_number' => '6C:3B:E5:27:D7:DD',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.15',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.4.155',]);
        DB::table('inventories')->insert([
            'product_name' => 'NPI9D491E',
            'product_vendor' => 'HP',
            'product_model' => 'M402n',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => '40:B0:34:9D:49:1E',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.15',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.4.165',]);
        DB::table('inventories')->insert([
            'product_name' => 'Cisco IP 7912',
            'product_vendor' => 'Cisco',
            'product_model' => '7912',
            'product_type' => 'Telefon',
            'product_number' => '00:15:63:AC:B4:4A',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.15',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.15.163',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-ET1-CAB1-16',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Pro 6300 MT',
            'product_type' => 'CALCULATOR',
            'product_number' => '74:46:A0:B6:93:5A',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.16',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.6.63',]);
        DB::table('inventories')->insert([
            'product_name' => 'NPI9D391C',
            'product_vendor' => 'HP',
            'product_model' => 'M402n',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => '40:B0:34:9D:39:1C',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.16',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.4.166',]);
        DB::table('inventories')->insert([
            'product_name' => 'Cisco IP 7912',
            'product_vendor' => 'Cisco',
            'product_model' => '7912',
            'product_type' => 'Telefon',
            'product_number' => '00:15:63:FF:5B:A2',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.16',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.15.164',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-ET1-CAB1-17',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Elite 8300 MT',
            'product_type' => 'CALCULATOR',
            'product_number' => '10:60:4B:83:6D:EC',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.17',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.4.87',]);
        DB::table('inventories')->insert([
            'product_name' => 'NPIA379EF',
            'product_vendor' => 'HP',
            'product_model' => 'M426dw',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => 'E4:E7:49:A3:79:EF',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.17',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.4.88',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'EPSON',
            'product_model' => 'LX350',
            'product_type' => 'IMPRIMANTA Matriciala  ',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.17',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => 'USB',]);
        DB::table('inventories')->insert([
            'product_name' => 'Cisco IP 7912',
            'product_vendor' => 'Cisco',
            'product_model' => '7912',
            'product_type' => 'Telefon',
            'product_number' => '00:11:20:DF:DD:99',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.17',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.15.65',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-ET1-CAB12',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Elite 8300 CMT',
            'product_type' => 'CALCULATOR',
            'product_number' => '24:BE:05:0C:E1:F9 ',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.18+1.19',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.3.54',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'HP',
            'product_model' => 'M428fdn',
            'product_type' => 'IMPRIMANTA Matriciala',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.18+1.19',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => 'USB',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'EPSON',
            'product_model' => 'LX350',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.18+1.19',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => 'USB',]);
        DB::table('inventories')->insert([
            'product_name' => 'Cisco IP 7912',
            'product_vendor' => 'Cisco',
            'product_model' => '7912',
            'product_type' => 'Telefon',
            'product_number' => '00:17:59:BE:72:EA',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.18+1.19',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.15.34',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-ET1-CAB1-20',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Pro 6300 MT',
            'product_type' => 'CALCULATOR',
            'product_number' => '74:46:A0:B6:8F:EE',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.20',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.6.141',]);
        DB::table('inventories')->insert([
            'product_name' => 'NPI9D39C8',
            'product_vendor' => 'HP',
            'product_model' => 'M402n',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => '40:B0:34:9D:39:C8',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.20',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.4.170',]);
        DB::table('inventories')->insert([
            'product_name' => 'Cisco IP 7912',
            'product_vendor' => 'Cisco',
            'product_model' => '7912',
            'product_type' => 'Telefon',
            'product_number' => '00:15:C6:17:CF:2F',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'CAB 1.20',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.15.67',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-Proiect-Adam',
            'product_vendor' => '',
            'product_model' => '',
            'product_type' => 'CALCULATOR',
            'product_number' => '74:46:A0:B6:8F:EE',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'EKG+SPIROMETRIE',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.1.149',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-ET1-REC01',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Elite 8300 MT',
            'product_type' => 'CALCULATOR',
            'product_number' => '10:60:4B:83:72:B1',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'RECEPTIE+ HOL ASTEPTARE ETAJ 1',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.3.56',]);
        DB::table('inventories')->insert([
            'product_name' => 'Receptie-HP428-Et1',
            'product_vendor' => 'HP',
            'product_model' => 'M428dw',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => 'F8:B4:6A:85:50:28',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'RECEPTIE+ HOL ASTEPTARE ETAJ 1',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.3.67',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'EPSON',
            'product_model' => 'LX350',
            'product_type' => 'IMPRIMANTA Matriciala',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'RECEPTIE+ HOL ASTEPTARE ETAJ 1',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => 'USB',]);
        DB::table('inventories')->insert([
            'product_name' => 'Cisco IP 7912',
            'product_vendor' => 'Cisco',
            'product_model' => '7912',
            'product_type' => 'Telefon',
            'product_number' => '00:14:F2:75:2A:8F',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'RECEPTIE+ HOL ASTEPTARE ETAJ 1',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.15.102',]);
        DB::table('inventories')->insert([
            'product_name' => 'DATECS LTD DP25',
            'product_vendor' => 'DATECS',
            'product_model' => 'DP25',
            'product_type' => 'Casa de marcat',
            'product_number' => '68:AA:D2:15:0F:D5',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'RECEPTIE+ HOL ASTEPTARE ETAJ 1',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.5.73',]);
        DB::table('inventories')->insert([
            'product_name' => 'D-Link DGS-108 Gigabit',
            'product_vendor' => 'D-LINK',
            'product_model' => 'DGS-108',
            'product_type' => 'SWITCH',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'RECEPTIE+ HOL ASTEPTARE ETAJ 1',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-ET1-CAB1-11',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Elite 8300 CMT
        ',
            'product_type' => 'CALCULATOR',
            'product_number' => '6C:3B:E5:1E:C1:47',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'RECEPTIE+ HOL ASTEPTARE ETAJ 1 ARIPA NOUA',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.6.117',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'HP',
            'product_model' => '',
            'product_type' => 'IMPRIMANTA',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'RECEPTIE+ HOL ASTEPTARE ETAJ 1 ARIPA NOUA',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => 'USB',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'EPSON',
            'product_model' => 'LX350',
            'product_type' => 'IMPRIMANTA Matriciala',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'RECEPTIE+ HOL ASTEPTARE ETAJ 1 ARIPA NOUA',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => 'USB',]);
        DB::table('inventories')->insert([
            'product_name' => 'Cisco IP 7912',
            'product_vendor' => 'Cisco',
            'product_model' => '7912',
            'product_type' => 'Telefon',
            'product_number' => '00:11:20:4C:13:0E',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'RECEPTIE+ HOL ASTEPTARE ETAJ 1 ARIPA NOUA',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.15.85',]);
        DB::table('inventories')->insert([
            'product_name' => 'DATECS LTD DP25',
            'product_vendor' => 'DATECS',
            'product_model' => 'DP25',
            'product_type' => 'Casa de marcat',
            'product_number' => '68:AA:D2:15:10:00',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_1',
            'product_office' => 'RECEPTIE+ HOL ASTEPTARE ETAJ 1 ARIPA NOUA',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.5.70',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-ET2-CAB21A',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Elite 8300 CMT',
            'product_type' => 'CALCULATOR',
            'product_number' => '6C:3B:E5:1F:85:38',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'CAB 2.1',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.3.58',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'HP',
            'product_model' => 'P1102',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'CAB 2.1',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => 'USB',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'Panasonic',
            'product_model' => '',
            'product_type' => 'Telefon fix',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'CAB 2.1',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-ET1-CAB1-18',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Pro 6300 MT',
            'product_type' => 'CALCULATOR',
            'product_number' => '10:60:4B:7A:CB:D6',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'CAB 2.2',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.4.187',]);
        DB::table('inventories')->insert([
            'product_name' => 'NPI9D19A6',
            'product_vendor' => 'HP',
            'product_model' => 'M402n',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => '40:B0:34:9D:19:A6',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'CAB 2.2',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.4.189',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-ET2-CAB23',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Elite 8300 MT',
            'product_type' => 'CALCULATOR',
            'product_number' => '6C:3B:E5:35:D5:0C',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'CAB 2.3',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.5.122',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'HP',
            'product_model' => 'MFP M181fw',
            'product_type' => 'IMPRIMANTA',
            'product_number' => 'USB',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'CAB 2.3',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '203',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-ET2-CAB24',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Elite 8300 MT',
            'product_type' => 'CALCULATOR',
            'product_number' => '80:C1:6E:F1:B1:CF',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'CAB 2.4',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.3.75',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'HP',
            'product_model' => '107w',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'CAB 2.4',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => 'USB',]);
        DB::table('inventories')->insert([
            'product_name' => 'Cisco IP 7912',
            'product_vendor' => 'Cisco',
            'product_model' => '7912',
            'product_type' => 'Telefon',
            'product_number' => '00:14:F2:75:2A:78',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'CAB 2.4',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.15.113',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-ET2-CAB25',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Elite 8300 CMT',
            'product_type' => 'CALCULATOR',
            'product_number' => '10:60:4B:81:64:86',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'CAB 2.5',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.6.39',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'HP',
            'product_model' => '1102w',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'CAB 2.5',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => 'USB',]);
        DB::table('inventories')->insert([
            'product_name' => 'Cisco IP 7912',
            'product_vendor' => 'Cisco',
            'product_model' => '7912',
            'product_type' => 'Telefon',
            'product_number' => '00:14:A9:81:95:F0',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'CAB 2.5',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.15.110',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-ET2-STOM1',
            'product_vendor' => 'Gigabyte Tecohnology',
            'product_model' => 'H61M-S2PV',
            'product_type' => 'CALCULATOR',
            'product_number' => '50:E5:49:19:7E:1E',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'CAB 2.6',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.3.72',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-ET2-STOM2',
            'product_vendor' => 'Gigabyte Tecohnology',
            'product_model' => 'H61M-S1',
            'product_type' => 'CALCULATOR',
            'product_number' => '94:DE:80:52:AA:72',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'CAB 2.6',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.7.135',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-ET2-CAB27N',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Elite 8300 CMT',
            'product_type' => 'CALCULATOR',
            'product_number' => '80:C1:6E:FF:24:F9',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'CAB 2.7',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.3.146',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'HP',
            'product_model' => 'MFP 125mw',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'CAB 2.7',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => 'USB',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'EPSON',
            'product_model' => 'LQ350',
            'product_type' => 'IMPRIMANTA Matriciala',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'CAB 2.7',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => 'USB',]);
        DB::table('inventories')->insert([
            'product_name' => 'Cisco IP 7912',
            'product_vendor' => 'Cisco',
            'product_model' => '7912',
            'product_type' => 'Telefon',
            'product_number' => '00:12:01:B3:52:41',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'CAB 2.7',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.15.227',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-ET2-CAB2-9N',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Elite 8300 MT',
            'product_type' => 'CALCULATOR',
            'product_number' => '10:60:4B:8A:8F:76',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'CAB 2.8',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.5.129',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'HP',
            'product_model' => '107W',
            'product_type' => 'IMPRIMANTA',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'CAB 2.8',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => 'USB',]);
        DB::table('inventories')->insert([
            'product_name' => 'Cisco IP 7912',
            'product_vendor' => 'Cisco',
            'product_model' => '7912',
            'product_type' => 'Telefon',
            'product_number' => '00:17:59:6E:D2:D6',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'CAB 2.8',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.15.32',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'Netis',
            'product_model' => 'ST3108C',
            'product_type' => 'SWITCH',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'CAB 2.8',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-ET2-CAB29',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Elite 8300 CMT',
            'product_type' => 'CALCULATOR',
            'product_number' => '2C:44:FD:23:7E:6A',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'CAB 2.9',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.3.79',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'HP',
            'product_model' => 'P1102w',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'CAB 2.9',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => 'USB',]);
        DB::table('inventories')->insert([
            'product_name' => 'Cisco IP 7912',
            'product_vendor' => 'Cisco',
            'product_model' => '7912',
            'product_type' => 'Telefon',
            'product_number' => '00:17:59:82:A4:10',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'CAB 2.9',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.15.33',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-ET2-REC1
        ',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Elite 8300 CMT',
            'product_type' => 'CALCULATOR',
            'product_number' => '10:60:4B:85:60:B7',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'RECEPTIE+ HOL ASTEPTARE ETAJ 2',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.3.179',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-ET2-REC02
        ',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Elite 8300 CMT',
            'product_type' => 'CALCULATOR',
            'product_number' => '10:60:4B:79:6F:47',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'RECEPTIE+ HOL ASTEPTARE ETAJ 2',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.3.69',]);
        DB::table('inventories')->insert([
            'product_name' => 'HP-402-Receptie-Et2',
            'product_vendor' => 'HP',
            'product_model' => 'M402n',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => '80:CE:62:E4:2B:B2',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'RECEPTIE+ HOL ASTEPTARE ETAJ 2',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.2.220',]);
        DB::table('inventories')->insert([
            'product_name' => 'HPC3EBE5',
            'product_vendor' => 'HP',
            'product_model' => 'M428fdn',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => '6C:02:E0:C3:EB:E5',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'RECEPTIE+ HOL ASTEPTARE ETAJ 2',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.3.205',]);
        DB::table('inventories')->insert([
            'product_name' => '',
            'product_vendor' => 'EPSON',
            'product_model' => 'LX350',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'RECEPTIE+ HOL ASTEPTARE ETAJ 2',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => 'USB',]);
        DB::table('inventories')->insert([
            'product_name' => 'DATECS LTD DP25',
            'product_vendor' => 'DATECS ',
            'product_model' => 'DP25',
            'product_type' => 'Casa de marcat      ',
            'product_number' => '68:AA:D2:15:0F:BA',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'RECEPTIE+ HOL ASTEPTARE ETAJ 2',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.5.72',]);
        DB::table('inventories')->insert([
            'product_name' => 'Cisco IP SPA 504G',
            'product_vendor' => 'Cisco',
            'product_model' => 'SPA 504G',
            'product_type' => 'Telefon',
            'product_number' => '38:1C:1A:B7:3C:37',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'RECEPTIE+ HOL ASTEPTARE ETAJ 2',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.15.11',]);
        DB::table('inventories')->insert([
            'product_name' => 'Dlink-AIS03',
            'product_vendor' => 'D-Link',
            'product_model' => 'DGS-1210-20',
            'product_type' => 'SWITCH',
            'product_number' => 'A0:AB:1B:ED:FC:28',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'RECEPTIE+ HOL ASTEPTARE ETAJ 2',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.2.246',]);
        DB::table('inventories')->insert([
            'product_name' => 'TEW-731BR',
            'product_vendor' => 'TRENDnet, Inc.',
            'product_model' => 'N300',
            'product_type' => 'Router Wireless',
            'product_number' => 'D8:EB:97:29:10:F8',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_2',
            'product_office' => 'RECEPTIE+ HOL ASTEPTARE ETAJ 2',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.2.211',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-PAR-REC-01',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Elite 8300 CMT',
            'product_type' => 'CALCULATOR',
            'product_number' => '88:51:FB:51:54:8F',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'parter',
            'product_office' => 'RECEPTIE MICA ',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.3.35',]);
        DB::table('inventories')->insert([
            'product_name' => 'DATECS LTD DP25',
            'product_vendor' => 'DATECS ',
            'product_model' => 'DP25',
            'product_type' => 'Casa de marcat      ',
            'product_number' => '68:AA:D2:15:10:1A',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'parter',
            'product_office' => 'RECEPTIE MICA ',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.5.77',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-PAR-REC-02',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Elite 8300 CMT',
            'product_type' => 'CALCULATOR',
            'product_number' => '6C:3B:E5:21:1B:05',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'parter',
            'product_office' => 'RECEPTIE MICA ',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.2.78',]);
        DB::table('inventories')->insert([
            'product_name' => 'DATECS FP800',
            'product_vendor' => 'DATECS ',
            'product_model' => 'FP800',
            'product_type' => 'Imprimanta fiscala',
            'product_number' => '68:AA:D2:17:E3:FC',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'parter',
            'product_office' => 'RECEPTIE MICA ',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.5.78',]);
        DB::table('inventories')->insert([
            'product_name' => 'HPM428Etaj4',
            'product_vendor' => 'HP',
            'product_model' => 'M482fdn',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => 'F8:B4:6A:86:4B:10',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'parter',
            'product_office' => 'RECEPTIE MICA ',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.6.198',]);
        DB::table('inventories')->insert([
            'product_name' => 'Zebra GK420d',
            'product_vendor' => 'Zebra',
            'product_model' => 'GK420d',
            'product_type' => 'IMPRIMANTA Etichete ',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'parter',
            'product_office' => 'RECEPTIE MICA ',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => 'USB',]);
        DB::table('inventories')->insert([
            'product_name' => 'Dlink-ALX150',
            'product_vendor' => 'D-LINK',
            'product_model' => 'DGS-1210-20',
            'product_type' => 'SWITCH',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'parter',
            'product_office' => 'RECEPTIE MICA ',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.3.150',]);
        DB::table('inventories')->insert([
            'product_name' => 'Cisco IP SPA 504G',
            'product_vendor' => 'Cisco',
            'product_model' => 'SPA 504G',
            'product_type' => 'Telefon',
            'product_number' => '38:1C:1A:B7:38:0D',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'parter',
            'product_office' => 'RECEPTIE MICA ',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.15.10',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALXPARREC03',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Elite 8300 CMT',
            'product_type' => 'CALCULATOR',
            'product_number' => '74:46:A0:A2:19:E0',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'parter',
            'product_office' => 'RECEPTIE MARE',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.3.32',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALXPARREC04',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Elite 8300 CMT',
            'product_type' => 'CALCULATOR',
            'product_number' => '10:60:4B:81:77:04',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'parter',
            'product_office' => 'RECEPTIE MARE',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.3.33',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALXPARREC05',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Elite 8300 CMT',
            'product_type' => 'CALCULATOR',
            'product_number' => '74:46:A0:AB:E3:4A',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'parter',
            'product_office' => 'RECEPTIE MARE',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.2.74',]);
        DB::table('inventories')->insert([
            'product_name' => 'DATECS FP800',
            'product_vendor' => 'DATECS',
            'product_model' => 'FP800',
            'product_type' => 'Imprimanta fiscala',
            'product_number' => '68:AA:D2:17:E3:EC',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'parter',
            'product_office' => 'RECEPTIE MARE',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.5.76',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALXPARREC06',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Elite 8300 CMT',
            'product_type' => 'CALCULATOR',
            'product_number' => '6C:3B:E5:1E:E0:D2',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'parter',
            'product_office' => 'RECEPTIE MARE',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.3.27',]);
        DB::table('inventories')->insert([
            'product_name' => 'DATECS LTD DP25',
            'product_vendor' => 'DATECS',
            'product_model' => 'DP25',
            'product_type' => 'Casa de marcat',
            'product_number' => '68:AA:D2:23:20:06',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'parter',
            'product_office' => 'RECEPTIE MARE',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.5.84',]);
        DB::table('inventories')->insert([
            'product_name' => 'NPIE42B59',
            'product_vendor' => 'HP',
            'product_model' => 'M402n',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => '80:CE:62:E4:2B:59',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'parter',
            'product_office' => 'RECEPTIE MARE',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.2.222',]);
        DB::table('inventories')->insert([
            'product_name' => 'Cisco IP SPA 962',
            'product_vendor' => 'Cisco',
            'product_model' => 'SPA 962',
            'product_type' => 'Telefon',
            'product_number' => '00:0E:08:D9:59:DB',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'parter',
            'product_office' => 'RECEPTIE MARE',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.15.12',]);
        DB::table('inventories')->insert([
            'product_name' => 'Zebra GK420d',
            'product_vendor' => 'Zebra',
            'product_model' => 'GK420d',
            'product_type' => 'IMPRIMANTA Etichete ',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'parter',
            'product_office' => 'RECEPTIE MARE',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => 'USB',]);
        DB::table('inventories')->insert([
            'product_name' => 'Dlink-ReceptieMare',
            'product_vendor' => 'D-LINK',
            'product_model' => 'DGS-108',
            'product_type' => 'SWITCH',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'parter',
            'product_office' => 'RECEPTIE MARE',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '',]);
        DB::table('inventories')->insert([
            'product_name' => 'Netis ReceptieMare',
            'product_vendor' => 'Netis',
            'product_model' => 'ST3108C',
            'product_type' => 'SWITCH',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'parter',
            'product_office' => 'RECEPTIE MARE',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-ET3-RAPORT1',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP ProDesk 600 G4 MT',
            'product_type' => 'CALCULATOR',
            'product_number' => 'C8:D9:D2:22:19:A9',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_3',
            'product_office' => 'RAPORTARE',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.7.191',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-ET3-RAPORT',
            'product_vendor' => 'MSI',
            'product_model' => 'MS-7817',
            'product_type' => 'CALCULATOR',
            'product_number' => '44:8A:5B:CA:44:6A',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_3',
            'product_office' => 'RAPORTARE',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.3.99',]);
        DB::table('inventories')->insert([
            'product_name' => 'Raportare 2',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Compaq Elite 8300 CMT',
            'product_type' => 'CALCULATOR',
            'product_number' => '24:BE:05:0B:27:D3',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_3',
            'product_office' => 'RAPORTARE',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.3.91',]);
        DB::table('inventories')->insert([
            'product_name' => 'MM-SILVANA',
            'product_vendor' => 'Dell Inc.',
            'product_model' => 'Inspiron 5505',
            'product_type' => 'LAPTOP',
            'product_number' => '5C:BA:EF:C7:E4:49',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_3',
            'product_office' => 'RAPORTARE',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.7.165',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-ET3-Raportare-HP428',
            'product_vendor' => 'HP',
            'product_model' => 'M428dw',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => 'F8:B4:6A:0B:09:38',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_3',
            'product_office' => 'RAPORTARE',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.5.50',]);
        DB::table('inventories')->insert([
            'product_name' => 'Cisco IP 7912',
            'product_vendor' => 'Cisco',
            'product_model' => '7912',
            'product_type' => 'Telefon      ',
            'product_number' => '00:14:A8:AC:A1:FC',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_3',
            'product_office' => 'RAPORTARE',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.15.120',]);
        DB::table('inventories')->insert([
            'product_name' => 'TP-Link TL SF1016D',
            'product_vendor' => 'TP-Link',
            'product_model' => 'TL SF1016D',
            'product_type' => 'SWITCH      ',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_3',
            'product_office' => 'RAPORTARE',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '',]);
        DB::table('inventories')->insert([
            'product_name' => 'ALX-ET3-RAIL',
            'product_vendor' => 'MSI',
            'product_model' => 'MS-7817',
            'product_type' => 'CALCULATOR',
            'product_number' => '44:8A:5B:CA:45:26',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_3',
            'product_office' => 'BIROU Calin+Georgescu',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.3.64',]);
        DB::table('inventories')->insert([
            'product_name' => 'ASOCIATIE-PC',
            'product_vendor' => 'Dell Inc.',
            'product_model' => 'Latitude 3560',
            'product_type' => 'LAPTOP',
            'product_number' => '14:18:77:9A:86:1F',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_3',
            'product_office' => 'BIROU Calin+Georgescu',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.3.17',]);
        DB::table('inventories')->insert([
            'product_name' => 'Cisco IP SPA 504G',
            'product_vendor' => 'Cisco',
            'product_model' => 'SPA 504G',
            'product_type' => 'Telefon      ',
            'product_number' => '38:1C:1A:B7:54:95',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_3',
            'product_office' => 'BIROU Calin+Georgescu',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.15.15',]);
        DB::table('inventories')->insert([
            'product_name' => 'D-Link DGS-1008D',
            'product_vendor' => 'D-Link',
            'product_model' => 'DGS-1008D',
            'product_type' => 'SWITCH      ',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_3',
            'product_office' => 'BIROU Calin+Georgescu',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '',]);
        DB::table('inventories')->insert([
            'product_name' => 'SECRETARIAT',
            'product_vendor' => 'MSI',
            'product_model' => 'MS-7817',
            'product_type' => 'CALCULATOR',
            'product_number' => '44:8A:5B:CA:47:8F',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_3',
            'product_office' => 'SECRETARIAT',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.7.180',]);
        DB::table('inventories')->insert([
            'product_name' => 'HP M277dw',
            'product_vendor' => 'HP',
            'product_model' => 'M277dw',
            'product_type' => 'IMPRIMANTA      ',
            'product_number' => '',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_3',
            'product_office' => 'SECRETARIAT',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => 'USB',]);
        DB::table('inventories')->insert([
            'product_name' => 'Cisco IP 7912',
            'product_vendor' => 'Cisco',
            'product_model' => '7912',
            'product_type' => 'Telefon',
            'product_number' => '00:18:BA:74:3C:C1',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_3',
            'product_office' => 'SECRETARIAT',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.15.121',]);
        DB::table('inventories')->insert([
            'product_name' => 'PRESEDINTE_AIS',
            'product_vendor' => 'Hewlett-Packard',
            'product_model' => 'HP Z220 CMT Workstation',
            'product_type' => 'CALCULATOR',
            'product_number' => '6C:3B:E5:35:8B:0A',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_3',
            'product_office' => 'BIROU DL. PRESEDINTE',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.6.153',]);
        DB::table('inventories')->insert([
            'product_name' => 'Cisco IP SPA 504G',
            'product_vendor' => 'Cisco',
            'product_model' => 'Cisco IP SPA 504G',
            'product_type' => 'Telefon',
            'product_number' => '38:1C:1A:B7:54:8D',
            'product_location' => 'alexandriei_144',
            'product_floor' => 'etaj_3',
            'product_office' => 'BIROU DL. PRESEDINTE',
            'product_purchase_date' => '2023-02-01',
            'ip_address' => '192.168.15.16',]);
                  
        
    }
}
